// Demo reports + audit logs for the seed-data expansion (#632) — the
// original seed only reset tables, since real flows normally populate them.
// Covers all 7 targetTypes and both sources (USER/SYSTEM). targetId for
// PROVIDER/REVIEW/JOB reference real seeded ids (prov_*/rev_*/job_*);
// WORK_PHOTO/INQUIRY/MESSAGE/JOB_RESPONSE ids are cuid()-generated by their
// owning service at insert time and unknowable across DBs at seed time, so
// those use clearly-synthetic placeholder ids (no FK enforces this — the
// real app already handles "reported content no longer exists").
const { PrismaClient } = require("@prisma/client");
const { PrismaPg } = require("@prisma/adapter-pg");

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const db = new PrismaClient({ adapter });

const REPORTS = [
  { id: "report_001", targetType: "PROVIDER", targetId: "prov_nuwan", ownerService: "provider", reporterId: "user_ashan", reason: "scam", details: "Flagged this because it looked off — please take a look.", status: "OPEN", source: "USER", resolvedBy: null, resolvedAt: null },
  { id: "report_002", targetType: "PROVIDER", targetId: "prov_p008", ownerService: "provider", reporterId: "user_c008", reason: "offensive", details: "Flagged this because it looked off — please take a look.", status: "OPEN", source: "USER", resolvedBy: null, resolvedAt: null },
  { id: "report_003", targetType: "PROVIDER", targetId: "prov_p015", ownerService: "provider", reporterId: "user_c015", reason: "fake", details: "Flagged this because it looked off — please take a look.", status: "RESOLVED", source: "USER", resolvedBy: "user_support_01", resolvedAt: new Date("2026-04-14T14:00:00Z") },
  { id: "report_004", targetType: "PROVIDER", targetId: "prov_p022", ownerService: "provider", reporterId: "user_c022", reason: "other", details: "Flagged this because it looked off — please take a look.", status: "RESOLVED", source: "USER", resolvedBy: "user_admin", resolvedAt: new Date("2026-05-15T14:00:00Z") },
  { id: "report_005", targetType: "PROVIDER", targetId: "prov_p029", ownerService: "provider", reporterId: null, reason: "auto-flag: suspicious contact info pattern", details: null, status: "RESOLVED", source: "SYSTEM", resolvedBy: "user_admin", resolvedAt: new Date("2026-06-16T14:00:00Z") },
  { id: "report_006", targetType: "PROVIDER", targetId: "prov_p036", ownerService: "provider", reporterId: "user_ashan", reason: "scam", details: "Flagged this because it looked off — please take a look.", status: "DISMISSED", source: "USER", resolvedBy: "user_support_01", resolvedAt: new Date("2026-01-17T14:00:00Z") },
  { id: "report_007", targetType: "WORK_PHOTO", targetId: "seed-photo-0", ownerService: "provider", reporterId: "user_c008", reason: "offensive", details: "Flagged this because it looked off — please take a look.", status: "DISMISSED", source: "USER", resolvedBy: "user_admin", resolvedAt: new Date("2026-02-18T14:00:00Z") },
  { id: "report_008", targetType: "WORK_PHOTO", targetId: "seed-photo-1", ownerService: "provider", reporterId: "user_c015", reason: "fake", details: "Flagged this because it looked off — please take a look.", status: "OPEN", source: "USER", resolvedBy: null, resolvedAt: null },
  { id: "report_009", targetType: "WORK_PHOTO", targetId: "seed-photo-2", ownerService: "provider", reporterId: "user_c022", reason: "other", details: "Flagged this because it looked off — please take a look.", status: "OPEN", source: "USER", resolvedBy: null, resolvedAt: null },
  { id: "report_010", targetType: "WORK_PHOTO", targetId: "seed-photo-3", ownerService: "provider", reporterId: null, reason: "auto-flag: content filter match", details: null, status: "OPEN", source: "SYSTEM", resolvedBy: null, resolvedAt: null },
  { id: "report_011", targetType: "INQUIRY", targetId: "seed-inquiry-0", ownerService: "provider", reporterId: "user_ashan", reason: "scam", details: "Flagged this because it looked off — please take a look.", status: "RESOLVED", source: "USER", resolvedBy: "user_admin", resolvedAt: new Date("2026-06-13T14:00:00Z") },
  { id: "report_012", targetType: "INQUIRY", targetId: "seed-inquiry-1", ownerService: "provider", reporterId: "user_c008", reason: "offensive", details: "Flagged this because it looked off — please take a look.", status: "RESOLVED", source: "USER", resolvedBy: "user_support_01", resolvedAt: new Date("2026-01-14T14:00:00Z") },
  { id: "report_013", targetType: "INQUIRY", targetId: "seed-inquiry-2", ownerService: "provider", reporterId: "user_c015", reason: "fake", details: "Flagged this because it looked off — please take a look.", status: "RESOLVED", source: "USER", resolvedBy: "user_admin", resolvedAt: new Date("2026-02-15T14:00:00Z") },
  { id: "report_014", targetType: "INQUIRY", targetId: "seed-inquiry-3", ownerService: "provider", reporterId: "user_c022", reason: "other", details: "Flagged this because it looked off — please take a look.", status: "DISMISSED", source: "USER", resolvedBy: "user_admin", resolvedAt: new Date("2026-03-16T14:00:00Z") },
  { id: "report_015", targetType: "MESSAGE", targetId: "seed-message-0", ownerService: "provider", reporterId: null, reason: "auto-flag: high report count in 24h", details: null, status: "DISMISSED", source: "SYSTEM", resolvedBy: "user_support_01", resolvedAt: new Date("2026-04-17T14:00:00Z") },
  { id: "report_016", targetType: "MESSAGE", targetId: "seed-message-1", ownerService: "provider", reporterId: "user_ashan", reason: "scam", details: "Flagged this because it looked off — please take a look.", status: "OPEN", source: "USER", resolvedBy: null, resolvedAt: null },
  { id: "report_017", targetType: "MESSAGE", targetId: "seed-message-2", ownerService: "provider", reporterId: "user_c008", reason: "offensive", details: "Flagged this because it looked off — please take a look.", status: "OPEN", source: "USER", resolvedBy: null, resolvedAt: null },
  { id: "report_018", targetType: "REVIEW", targetId: "rev_1", ownerService: "review", reporterId: "user_c015", reason: "fake", details: "Flagged this because it looked off — please take a look.", status: "OPEN", source: "USER", resolvedBy: null, resolvedAt: null },
  { id: "report_019", targetType: "REVIEW", targetId: "rev_18", ownerService: "review", reporterId: "user_c022", reason: "other", details: "Flagged this because it looked off — please take a look.", status: "RESOLVED", source: "USER", resolvedBy: "user_admin", resolvedAt: new Date("2026-02-12T14:00:00Z") },
  { id: "report_020", targetType: "REVIEW", targetId: "rev_35", ownerService: "review", reporterId: null, reason: "auto-flag: suspicious contact info pattern", details: null, status: "RESOLVED", source: "SYSTEM", resolvedBy: "user_admin", resolvedAt: new Date("2026-03-13T14:00:00Z") },
  { id: "report_021", targetType: "REVIEW", targetId: "rev_52", ownerService: "review", reporterId: "user_ashan", reason: "scam", details: "Flagged this because it looked off — please take a look.", status: "RESOLVED", source: "USER", resolvedBy: "user_support_01", resolvedAt: new Date("2026-04-14T14:00:00Z") },
  { id: "report_022", targetType: "REVIEW", targetId: "rev_69", ownerService: "review", reporterId: "user_c008", reason: "offensive", details: "Flagged this because it looked off — please take a look.", status: "DISMISSED", source: "USER", resolvedBy: "user_admin", resolvedAt: new Date("2026-05-15T14:00:00Z") },
  { id: "report_023", targetType: "REVIEW", targetId: "rev_86", ownerService: "review", reporterId: "user_c015", reason: "fake", details: "Flagged this because it looked off — please take a look.", status: "DISMISSED", source: "USER", resolvedBy: "user_admin", resolvedAt: new Date("2026-06-16T14:00:00Z") },
  { id: "report_024", targetType: "JOB", targetId: "job_001", ownerService: "job", reporterId: "user_c022", reason: "other", details: "Flagged this because it looked off — please take a look.", status: "OPEN", source: "USER", resolvedBy: null, resolvedAt: null },
  { id: "report_025", targetType: "JOB", targetId: "job_006", ownerService: "job", reporterId: null, reason: "auto-flag: content filter match", details: null, status: "OPEN", source: "SYSTEM", resolvedBy: null, resolvedAt: null },
  { id: "report_026", targetType: "JOB", targetId: "job_011", ownerService: "job", reporterId: "user_ashan", reason: "scam", details: "Flagged this because it looked off — please take a look.", status: "OPEN", source: "USER", resolvedBy: null, resolvedAt: null },
  { id: "report_027", targetType: "JOB", targetId: "job_016", ownerService: "job", reporterId: "user_c008", reason: "offensive", details: "Flagged this because it looked off — please take a look.", status: "RESOLVED", source: "USER", resolvedBy: "user_support_01", resolvedAt: new Date("2026-04-11T14:00:00Z") },
  { id: "report_028", targetType: "JOB", targetId: "job_021", ownerService: "job", reporterId: "user_c015", reason: "fake", details: "Flagged this because it looked off — please take a look.", status: "RESOLVED", source: "USER", resolvedBy: "user_admin", resolvedAt: new Date("2026-05-12T14:00:00Z") },
  { id: "report_029", targetType: "JOB_RESPONSE", targetId: "seed-job-response-0", ownerService: "job", reporterId: "user_c022", reason: "other", details: "Flagged this because it looked off — please take a look.", status: "RESOLVED", source: "USER", resolvedBy: "user_admin", resolvedAt: new Date("2026-06-13T14:00:00Z") },
  { id: "report_030", targetType: "JOB_RESPONSE", targetId: "seed-job-response-1", ownerService: "job", reporterId: null, reason: "auto-flag: high report count in 24h", details: null, status: "DISMISSED", source: "SYSTEM", resolvedBy: "user_support_01", resolvedAt: new Date("2026-01-14T14:00:00Z") },
  { id: "report_031", targetType: "JOB_RESPONSE", targetId: "seed-job-response-2", ownerService: "job", reporterId: "user_ashan", reason: "scam", details: "Flagged this because it looked off — please take a look.", status: "DISMISSED", source: "USER", resolvedBy: "user_admin", resolvedAt: new Date("2026-02-15T14:00:00Z") },
];

const AUDIT_LOGS = [
  { id: "audit_001", adminId: "user_support_01", action: "resolve_report", targetType: "PROVIDER", targetId: "prov_nuwan", reason: "Repeated user reports over the past week.", service: "trust-safety" },
  { id: "audit_002", adminId: "user_admin", action: "dismiss_report", targetType: "PROVIDER", targetId: "prov_p012", reason: null, service: "trust-safety" },
  { id: "audit_003", adminId: "user_admin", action: "suspend_provider", targetType: "PROVIDER", targetId: "prov_p023", reason: "Repeated user reports over the past week.", service: "provider" },
  { id: "audit_004", adminId: "user_support_01", action: "restore_provider", targetType: "PROVIDER", targetId: "prov_p034", reason: null, service: "provider" },
  { id: "audit_005", adminId: "user_admin", action: "takedown_review", targetType: "REVIEW", targetId: "rev_45", reason: "Repeated user reports over the past week.", service: "review" },
  { id: "audit_006", adminId: "user_admin", action: "restore_review", targetType: "REVIEW", targetId: "rev_56", reason: null, service: "review" },
  { id: "audit_007", adminId: "user_support_01", action: "hide_job", targetType: "JOB", targetId: "job_027", reason: "Repeated user reports over the past week.", service: "job" },
  { id: "audit_008", adminId: "user_admin", action: "resolve_report", targetType: "PROVIDER", targetId: "prov_p028", reason: null, service: "trust-safety" },
  { id: "audit_009", adminId: "user_admin", action: "dismiss_report", targetType: "PROVIDER", targetId: "prov_p039", reason: "Repeated user reports over the past week.", service: "trust-safety" },
  { id: "audit_010", adminId: "user_support_01", action: "suspend_provider", targetType: "PROVIDER", targetId: "prov_p050", reason: null, service: "provider" },
  { id: "audit_011", adminId: "user_admin", action: "restore_provider", targetType: "PROVIDER", targetId: "prov_p011", reason: "Repeated user reports over the past week.", service: "provider" },
  { id: "audit_012", adminId: "user_admin", action: "takedown_review", targetType: "REVIEW", targetId: "rev_122", reason: null, service: "review" },
  { id: "audit_013", adminId: "user_support_01", action: "restore_review", targetType: "REVIEW", targetId: "rev_133", reason: "Repeated user reports over the past week.", service: "review" },
  { id: "audit_014", adminId: "user_admin", action: "hide_job", targetType: "JOB", targetId: "job_024", reason: null, service: "job" },
  { id: "audit_015", adminId: "user_admin", action: "resolve_report", targetType: "PROVIDER", targetId: "prov_rizwan", reason: "Repeated user reports over the past week.", service: "trust-safety" },
];

// ---------------------------------------------------------------------------
// #632 seed-data expansion — batch 2 ("demo everything" scale). GENERATED
// reports report_032..report_073 continue the report_NNN scheme, cycling all 7
// targetTypes, all 3 statuses and both sources, referencing the newly seeded
// providers/reviews/jobs (prov_p051+/rev_151+/job_041+) and synthetic ids for
// the cross-DB target types (continuing the seed-photo-/seed-inquiry-/seed-
// message-/seed-job-response- placeholder scheme). GENERATED audit logs
// continue audit_NNN. Each OPEN+reporter row uses a unique (targetType,
// targetId) so the partial-unique dedup index is never tripped.
// ---------------------------------------------------------------------------
const gPad3 = (n) => String(n).padStart(3, "0");
const TARGET_TYPES = ["PROVIDER", "WORK_PHOTO", "INQUIRY", "MESSAGE", "REVIEW", "JOB", "JOB_RESPONSE"];
const OWNER_OF = { PROVIDER: "provider", WORK_PHOTO: "provider", INQUIRY: "provider", MESSAGE: "provider", REVIEW: "review", JOB: "job", JOB_RESPONSE: "job" };
const STATUSES = ["OPEN", "RESOLVED", "DISMISSED"];
const USER_REASONS = ["spam", "scam", "offensive", "fake", "other"];
const SYS_REASONS = ["auto-flag: content filter match", "auto-flag: suspicious contact info pattern", "auto-flag: high report count in 24h"];
const REPORTERS = ["user_ashan", "user_c008", "user_c015", "user_c022", "user_c035", "user_c048", "user_c060", "user_c072"];
const RESOLVERS = ["user_admin", "user_support_01"];
function genTargetId(type, m) {
  switch (type) {
    case "PROVIDER": return `prov_p${gPad3(51 + (m % 100))}`;
    case "REVIEW": return `rev_${151 + (m % 350)}`;
    case "JOB": return `job_${gPad3(41 + (m % 40))}`;
    case "WORK_PHOTO": return `seed-photo-${4 + m}`;
    case "INQUIRY": return `seed-inquiry-${4 + m}`;
    case "MESSAGE": return `seed-message-${3 + m}`;
    case "JOB_RESPONSE": return `seed-job-response-${3 + m}`;
    default: return `seed-${m}`;
  }
}
const GEN_REPORTS = Array.from({ length: 42 }, (_, m) => {
  const targetType = TARGET_TYPES[m % TARGET_TYPES.length];
  const source = m % 4 === 0 ? "SYSTEM" : "USER";
  const status = STATUSES[m % STATUSES.length];
  const resolved = status !== "OPEN";
  return {
    id: `report_${gPad3(32 + m)}`,
    targetType,
    targetId: genTargetId(targetType, m),
    ownerService: OWNER_OF[targetType],
    reporterId: source === "SYSTEM" ? null : REPORTERS[m % REPORTERS.length],
    reason: source === "SYSTEM" ? SYS_REASONS[m % SYS_REASONS.length] : USER_REASONS[m % USER_REASONS.length],
    details: source === "SYSTEM" ? null : "Flagged this because it looked off — please take a look.",
    status,
    source,
    resolvedBy: resolved ? RESOLVERS[m % RESOLVERS.length] : null,
    resolvedAt: resolved ? new Date(`2026-0${(m % 6) + 1}-1${m % 9}T14:00:00Z`) : null,
  };
});

const GEN_AUDIT_ACTIONS = [
  ["resolve_report", "PROVIDER", "trust-safety"],
  ["dismiss_report", "REVIEW", "trust-safety"],
  ["suspend_provider", "PROVIDER", "provider"],
  ["restore_provider", "PROVIDER", "provider"],
  ["takedown_review", "REVIEW", "review"],
  ["restore_review", "REVIEW", "review"],
  ["hide_job", "JOB", "job"],
  ["unhide_job", "JOB", "job"],
  ["delete_photo", "WORK_PHOTO", "provider"],
  ["restore_photo", "WORK_PHOTO", "provider"],
];
const GEN_AUDIT_LOGS = Array.from({ length: 15 }, (_, m) => {
  const [action, targetType, service] = GEN_AUDIT_ACTIONS[m % GEN_AUDIT_ACTIONS.length];
  let targetId;
  if (targetType === "PROVIDER") targetId = `prov_p${gPad3(51 + (m % 100))}`;
  else if (targetType === "REVIEW") targetId = `rev_${151 + (m % 350)}`;
  else if (targetType === "JOB") targetId = `job_${gPad3(41 + (m % 40))}`;
  else targetId = `seed-photo-${50 + m}`;
  return {
    id: `audit_${gPad3(16 + m)}`,
    adminId: RESOLVERS[m % RESOLVERS.length],
    action,
    targetType,
    targetId,
    reason: m % 2 === 0 ? "Repeated user reports over the past week." : null,
    service,
  };
});

async function main() {
  if (process.env.NODE_ENV === "production" && process.env.SEED_DEMO_DATA !== "true") {
    console.error(
      "Refusing to seed trust-safety demo data with NODE_ENV=production " +
        "(set SEED_DEMO_DATA=true to override deliberately)."
    );
    process.exitCode = 1;
    return;
  }
  await db.report.deleteMany();
  await db.adminAuditLog.deleteMany();

  for (const r of [...REPORTS, ...GEN_REPORTS]) {
    await db.report.create({ data: r });
  }
  for (const a of [...AUDIT_LOGS, ...GEN_AUDIT_LOGS]) {
    await db.adminAuditLog.create({ data: a });
  }

  const totalReports = REPORTS.length + GEN_REPORTS.length;
  const totalAudit = AUDIT_LOGS.length + GEN_AUDIT_LOGS.length;
  console.log(`Seeded ${totalReports} reports and ${totalAudit} audit log entries.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(() => db.$disconnect());
